var preguntas = 
	[{	tipo: "Planificación",
		preguntas: [
			{	pregunta: "Para usted, ¿Que es objetivo?",
				opciones: ["Un enunciado detallado, preciso y medible de los resultados esperados.",
							"Lo que se pretende hacer, no importa lo imposible que parezca",
							"la intención de desarrollar un proyecto"],
				correcta: 0
			},
			{	pregunta: "Identifique cual es el primer paso del proceso de la planeación de una organización",
				opciones: ["Fijar una meta útil",
							"Determinar el tiempo que se debe tardar lo planeado",
							"Establecer los indicadores para medir los resultados "],
				correcta: 0
			},
			{	pregunta: "¿Cuál de las siguientes opciones es la tarea básica de la Planeación?",
				opciones: ["Diseñar una situación óptima. ",
							"Proyectar un futuro deseado y los medios para conseguirlo",
							"Formular el mejor modelo de desarrollo. ",
							"Discutir un problema y encontrarle solución. "],
				correcta: 0
			},
			{	pregunta: "¿En qué circunstancias se debe ejercitar la Planeación?",
				opciones: ["Cuando ya se tengan resultados. ",
							"No importa el tiempo, siempre se aplica ",
							"Antes de que se inicien las acciones del proyecto ",
							"Un tiempo después de iniciadas las acciones. "],
				correcta: 0
			},
			{	pregunta: "¿En qué circunstancias tiene posibilidades de influir la Planeación? ",
				opciones: ["Cuando incremente las posibilidades de alcanzar los objetivos. ",
							"En los sistemas creados por la naturaleza",
							"En los sistemas cuyo futuro es imposible de moldear. ",
							"En aquellos sistemas que el hombre no puede modificar. "],
				correcta: 0
			},
			{	pregunta: "Cuál de los siguientes índices de rentabilidad de inversiones se puede expresar en años",
				opciones: ["La Tasa Interna de Rendimiento (TIR)",
							"El Valor Actual Neto (VAN)",
							"Todos los índices",
							"El Plazo de Recuperación "],
				correcta: 0
			},
			{	pregunta: "Indique el concepto de inversión, entre las siguientes opciones:",
				opciones: ["La adquisición de títulos-valores",
							"Todos los gastos del grupo 6 del Plan General de Contabilidad",
							"El acto de aplicar recursos al mantenimiento y ampliación del capital productivo.",
							"La compra de bienes y servicios por parte de la empresa"],
				correcta: 0
			},
			{	pregunta: "Señala la respuesta correcta:",
				opciones: ["Con las inversiones productivas se adquieren activos como acciones, obligaciones, bonos, etc.",
							"Una inversión en elementos de transporte la podemos clasificar como inversión de activo circulante",
							"Con las inversiones financieras se adquieren activos como materias primas, mercaderías, mobiliario, elementos de transporte, etc.",
							"Una de las clasificaciones de las inversiones distingue entre inversiones de activo fijo e inversiones de activo circulante"],
				correcta: 0
			},
			{	pregunta: "Si tuviéramos que invertir en varios proyectos de inversión alternativos, aplicando el método VAN, nos decidiríamos por:.",
				opciones: ["Invertir en el proyecto cuyo VAN sea mayor",
							"Invertir en el proyecto cuyo VAN sea menor",
							"Invertir en el proyecto cuyo VAN sea igual a cero",
							"Invertir en el proyecto cuyo VAN sea negativo"],
				correcta: 0
			}]
	},
	{	tipo: "Organizacion",
		preguntas: [
			{	pregunta: "Para usted, ¿Cuál debe ser la principal función de la empresa?",
				opciones: ["La de producir la mayor cantidad de productos posible",
							"La de producir los bienes y servicios necesarios para satisfacer las necesidades humanas.",
							"La de obtención del máximo beneficio para el accionista",
							"La de creación de empleo"],
				correcta: 0
			},
			{	pregunta: "El objetivo fundamental de la empresa, definida como unidad económica de producción es:",
				opciones: ["La transformación de la materia prima",
							"La producción de bienes de consumo",
							"La producción de bienes intermedios",
							"La creación de utilidad"],
				correcta: 0
			},
			{	pregunta: "Desde el punto de vista social el empresario es, ante todo:",
				opciones: ["El director financiero",
							"El propietario de la empresa",
							"El que posee acciones de la empresa",
							"El que asume la responsabilidad de la gestión de la empresa"],
				correcta: 0
			},
			{	pregunta: "¿Qué entiende por demanda de un bien?",
				opciones: ["La cantidad que de dicho bien adquiere el consumidor a un determinado precio",
							"La cantidad de producto que se encuentra en el mercado",
							"Los gustos de los consumidores",
							"El volumen de ventas de una empresa"],
				correcta: 0
			},
			{	pregunta: "Un mercado es toda institución social en la que los agentes independientes:",
				opciones: ["Fabrican productos intermedios",
							"Exponen sus productos para la venta",
							"Van a comprar lo que necesitan",
							"Intercambian libremente bienes y factores productivos"],
				correcta: 0
			},
			{	pregunta: "A la empresa se la define como:",
				opciones: ["La unidad económica de inversión",
							"La unidad económica de marketing",
							"La unidad económica de consumo",
							"La unidad económica de producción",],
				correcta: 0
			},
			{	pregunta: "¿Qué es una empresa pública?",
				opciones: ["Aquella que ofrece bienes públicos en el mercado",
							"Aquella en la que puede entrar cualquier persona",
							"Aquella cuyo capital pertenece al Estado",
							"Aquella que recibe su capital de muchas personas"],
				correcta: 0
			},
			{	pregunta: "Indique que establece el principio de unidad de mando:",
				opciones: ["Una persona sólo debe recibir órdenes de un jefe",
							"En una empresa sólo una persona puede dar órdenes",
							"Existe una escala jerárquica que delimita quien ejerce la autoridad",
							"Se debe desarrollar un solo programa cuando las operaciones tienen un único fin."],
				correcta: 0
			},
			{	pregunta: "El elemento que transmite un mensaje hasta un receptor es:",
				opciones: ["Un transmisor",
							"Un ruido en la comunicación",
							"Un canal de comunicación",
							"Un correo"],
				correcta: 2
			},
			{	pregunta: "Si una empresa tuviese muchos puntos de venta, lo lógico sería hacer:",
				opciones: ["Una departamentalización geográfica",
							"Una departamentalización por funciones",
							"Una departamentalización por clientes",
							"Una departamentalización por productos"],
				correcta: 0
			},
			{	pregunta: "Desde su punto de vista de la administración de la empresa, organizar significa:",
				opciones: ["Atribuir un salario a cada trabajador en función de su puesto.",
							"Asignar a los recursos disponibles un papel concreto a desempeñar por cada uno",
							"Dividir la empresa en secciones y departamentos",
							"Determinar el número mínimo de subordinados que pueden depender de un superior"],
				correcta: 1			
			},
			{	pregunta: "La representación gráfica del conjunto de interrelaciones funcionales entre los departamentos de una empresa recibe el nombre de:",
				opciones: ["Diagrama de sectores",
							"Organigrama",
							"Profesiograma",
							"Anagrama"],
				correcta: 1,
			},
			{	pregunta: "Indique que representa el organigrama:",
				opciones: ["Ninguna es correcta",
							"La comunicación formal e informal que se produce en la organización",
							"El grado de especialización o ampliación de los puestos de trabajo",
							"Las relaciones jerárquicas entre los integrantes de la organización"],
				correcta: 3
			},
			{	pregunta: "El conjunto de personas sometidas a la autoridad de un superior conforma:",
				opciones: ["Un comité",
							"Un sindicato",
							"Un nivel de la organización",
							"Un área de mando"],
				correcta: 3
			},
			{	pregunta: "La función de organización tiene como contenido fundamental:",
				opciones: ["Comparar los resultados obtenidos con los que habían sido planificados",
							"Elegir al director general de la empresa",
							"Saber con antelación qué es lo que debe realizar la empresa",
							"La división y coordinación del trabajo"],
				correcta: 3
			},
			{	pregunta: "Para usted, El organigrama de una empresa refleja:",
				opciones: ["Proporciona una visión gráfica y resumida de la estructura informal de la organización",
							"El documento más importante de la empresa junto con el Balance",
							"Proporciona una visión gráfica y resumida de la estructura formal de la organización",
							"La interrelación entre los diferentes objetivos de la empresa"],
				correcta: 2
			}]},
	{	tipo: "Marketing",
		preguntas: [
			{	pregunta: "Las variables de marketing-mix son:",
				opciones: ["Producto, Precio, Promoción y Distribución",
							"Investigación y Segmentación de mercados",
							"Investigación comercial, canales de información, recepción de la información y tratamiento de la misma",
							"Publicidad, Promoción y Distribución"],
				correcta: 0
			},
			{	pregunta: "Indique cual es la finalidad de la investigación de mercados:",
				opciones: ["Proporcionar información sobre el mercado y el entorno",
							"Distribuir los bienes que fabrican las empresas",
							"Informar a los consumidores",
							"Dividir el mercado en subgrupos homogéneos para adaptar la estrategia comercial de la empresa"],
				correcta: 0
			},
			{	pregunta: "Dividir el mercado en subgrupos homogéneos con el fin de realizar estrategias comerciales diferenciadas, es:",
				opciones: ["Segmentar el mercado",
							"Promocionar el producto",
							"Investigar el mercado",
							"Diferenciar el producto"],
				corecta: 0
			},
			{	pregunta: "En la etapa de declive en el ciclo de vida de un producto:",
				opciones: ["Aparecen productos más competitivos",
							"La empresa obtiene el máximo nivel de ventas",
							"Se produce el apogeo de las campañas de promoción",
							"Las ventas se estabilizan"],
				correcta: 0
			},
			{	pregunta: "Introducción, crecimiento, madurez y declive, hacen referencia a:",
				opciones: ["La logística de la empresa",
							"La investigación de mercados",
							"La segmentación de mercados",
							"El ciclo de vida de los productos"],
				correcta: 3
			},
			{	pregunta: "La promoción de ventas consiste en:",
				opciones: ["Un conjunto de técnicas para crear unas determinadas relaciones y un clima de confianza tanto dentro como fuera de la empresa",
							"Un conjunto de técnicas para conseguir mediante una campaña temporal y espacial estimular la demanda y aumentar las ventas",
							"Un conjunto de técnicas para llevar el producto final del fabricante al minorista",
							"Un conjunto de técnicas encaminadas a recoger información del mercado a través de encuestas"],
				correcta: 1
			},
			{	pregunta: "Las etapas que definen el concepto de ciclo de vida de un producto son:",
				opciones: ["Introducción, decadencia y crisis",
							"Introducción y declive",
							"Introducción, crecimiento, madurez y declive",
							"Introducción, crecimiento y declive"],
				correcta: 2
			},
			{	pregunta: "Los mayoristas son intermediarios comerciales que:",
				opciones: ["Venden directamente al consumidor final",
							"Compran al fabricante para venderlo al consumidor final",
							"Fabrican grandes cantidades de productos",
							"Compran en grandes cantidades para vender a otros intermediarios"],
				correcta: 3
			},
		]
	}];
